return {
	package = {
		name = "MyProject",
		version = "0.1.0",
		dependencies = {
			["pretty-print"] = { rev = "main", sourceKind = "github", source = "https://github.com/afujiwara-roblox/pretty-print" },
			base64 = { rev = "main", sourceKind = "github", source = "https://github.com/afujiwara-roblox/base64" },
			toml = { rev = "main", sourceKind = "github", source = "https://github.com/afujiwara-roblox/toml" },
		},
	},
}
