return {
  version = 1,
  package = {
    {
      name = "base64",
      rev = "main",
      source = "https://github.com/afujiwara-roblox/base64/archive/main.zip",
      source_kind = "git",
    },
    {
      name = "pretty-print",
      rev = "main",
      source = "https://github.com/afujiwara-roblox/pretty-print/archive/main.zip",
      source_kind = "git",
    },
    {
      name = "toml",
      rev = "main",
      source = "https://github.com/afujiwara-roblox/toml/archive/main.zip",
      source_kind = "git",
    },
  },
}